#!/usr/bin/env bash

each_file() {
    src_file="${1}"
    gitignore="${2}"
    basedir="$(dirname "${1}")"
    c_filename="$(basename "${1}")"
    header_file="${basedir}/$(echo "${c_filename}" | sed -e s/\.c/\.h/ )"
    module_name="$(echo "${c_filename}" | sed -e s/\.test\.c// )"
    funcs="$(cat "${src_file}" | grep -E '^void tests_' | sed -e s/\ {/\;/ )"

    if [[ -z "${funcs}" ]] ; then
        return
    fi

    # ensure this header file is ignored
    echo "$(basename ${header_file})" >> "${gitignore}"

    if [ -f "${header_file}" ] && [[ "${header_file}" -nt "${src_file}" ]] ; then
        return
    fi

    {
        echo "/* Automatically generated by script/gen-test-headers.sh */"
        echo "#ifndef _BH_tests_${module_name}_h_"
        echo "#define _BH_tests_${module_name}_h_ 1"
        echo
        echo "#include \"main.h\""
        echo
        echo "#define setup_each    tests_bh_${module_name}_setup_each"
        echo "#define teardown_each tests_bh_${module_name}_teardown_each"
        echo
        echo "int tests_bh_${module_name}_setup_each(void **state);"
        echo "int tests_bh_${module_name}_teardown_each(void **state);"
        echo
        echo "${funcs}"
        echo
        echo "int main(void) {"
        echo "  static const struct CMUnitTest tests_bh_${module_name}[] = {"
        while read func
        do
            echo "    cmocka_unit_test_setup_teardown($(echo "${func}" | sed -e 's/void\ //g' -e 's/(.*);//'), setup_each, teardown_each),"
        done <<< "${funcs}"
        echo "  };"
        echo "  return cmocka_run_group_tests(tests_bh_${module_name}, NULL, NULL);"
        echo "}"
        echo
        echo "#undef setup_each"
        echo "#undef teardown_each"
        echo
        echo "#endif"
    } > "${header_file}"

    echo "${header_file}"
}


first=true
for f in ${*}
do
    # skip any file with 'test!skip-gen' in the first 10 lines
    [[ "$(head -n 10 "${f}" | grep 'test!skip-gen')" ]] && continue

    gitignore="$(dirname "${f}")/.gitignore"
    if [[ "${first}" == true ]]
    then
        echo "# Automatically generated by script/gen-test-headers.sh" > "${gitignore}"
        echo "# Commit this file into Git to ensure test header files are ignored" >> "${gitignore}"
        first=false
    fi

    each_file "${f}" "${gitignore}"
done
